version: '3.1'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    container_name: 'contacts-system-mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: contacts-system

  backend:
    image: leticiatakeshiro/contacts-system-backend:0.0.1
    ports:
      - '3000:3000'
    container_name: 'contacts-system-backend'
